module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.descriptions = [
    'Explore the beauty of nature at our scenic campgrounds, where tranquility meets adventure. Nestled among lush forests and serene landscapes, our campsites offer the perfect escape for families, friends, and solo travelers. Enjoy hiking, stargazing, and campfire moments under the open sky. Make unforgettable memories today!',
    'Enjoy a peaceful retreat at our campgrounds, surrounded by breathtaking views and the soothing sounds of nature. Whether you prefer quiet solitude or group activities, our sites cater to all needs. Experience the magic of the outdoors and create lasting memories with loved ones.',
    'Reconnect with nature at our cozy campgrounds, where you can unwind in the heart of the wilderness. Perfect for those seeking an immersive experience, our sites provide opportunities for wildlife spotting, fishing, and peaceful relaxation. Escape the hustle and bustle of everyday life.',
    'Our campgrounds offer a variety of options for outdoor enthusiasts. From rustic tent sites to fully equipped RV spots, there’s something for everyone. Gather around the fire, share stories, and bask in the natural beauty that surrounds you.',
    'Discover adventure at our vibrant campgrounds, featuring scenic trails and diverse outdoor activities. Whether you’re a seasoned camper or new to camping, our sites provide a welcoming space to immerse yourself in nature and enjoy outdoor fun.',
    'Camp beneath towering trees and experience the serenity of our well-maintained campgrounds. With amenities like clean restrooms and picnic areas, your stay will be comfortable and memorable. Perfect for family outings and group getaways.',
    'Step into a world of peaceful camping at our picturesque campgrounds, where comfort meets nature. Ideal for stargazing, photography, and relaxation, our sites offer an unforgettable experience in the great outdoors.',
    'Our family-friendly campgrounds are designed to provide fun and adventure for all ages. From interactive nature programs for kids to hiking trails for adults, there’s something for everyone to enjoy. Embrace the beauty of nature together.',
    'Enjoy a serene camping experience at our remote campgrounds, where the only sounds you’ll hear are those of birds and rustling leaves. Perfect for those looking to escape the noise of modern life and immerse themselves in nature’s calm.',
    'Escape to our tranquil campgrounds and immerse yourself in nature’s peaceful embrace. Our sites offer a variety of activities, from canoeing on nearby lakes to guided nature walks, ensuring an enriching and rejuvenating experience.',
    'Experience the charm of rustic camping at our secluded campgrounds. Surrounded by nature’s beauty, enjoy simple pleasures like storytelling, nature walks, and star-gazing around a crackling fire.',
    'Our adventure-packed campgrounds are ideal for thrill-seekers. From zip-lining and rock climbing to wildlife observation, every moment is filled with excitement and discovery.',
    'For a peaceful and romantic escape, our serene campgrounds offer cozy spots perfect for couples. Enjoy intimate moments by the fire or explore scenic trails hand in hand.',
    'Immerse yourself in the wild with our campgrounds designed for nature lovers. Spot unique wildlife, bird watch, and hike through scenic trails to connect with the great outdoors.',
    'Our family-oriented campgrounds provide a safe environment for children to explore while creating lasting memories with loved ones. From scavenger hunts to marshmallow roasting, there’s fun for everyone.',
    'Embrace eco-friendly camping at our sustainable campgrounds. Enjoy the beauty of nature while supporting environmentally responsible practices and reducing your ecological footprint.',
    'Experience the best of both worlds with our beachside campgrounds. Combine camping with beach activities like swimming, beachcombing, and evening bonfires for a perfect seaside retreat.',
    'Step back in time at our historical campgrounds. Learn about local history, heritage, and enjoy old-fashioned camping traditions amidst historic landmarks and landscapes.',
    'For those seeking peace and solitude, our quiet campgrounds offer the perfect setting for reflection and mindfulness. Disconnect from the world and rejuvenate in a calm natural environment.',
    'Our versatile campgrounds cater to both adventure seekers and relaxation enthusiasts. Whether you prefer thrilling outdoor activities or peaceful moments of stillness, there’s something for everyone.'
]