module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.descriptions = [
    'Explore the beauty of nature at our scenic campgrounds, where tranquility meets adventure. Nestled among lush forests and serene landscapes, our campsites offer the perfect escape for families, friends, and solo travelers. Enjoy hiking, stargazing, and campfire moments under the open sky. Make unforgettable memories today!',
    'Enjoy a peaceful retreat at our campgrounds, surrounded by breathtaking views and the soothing sounds of nature. Whether you prefer quiet solitude or group activities, our sites cater to all needs. Experience the magic of the outdoors and create lasting memories with loved ones.',
    'Reconnect with nature at our cozy campgrounds, where you can unwind in the heart of the wilderness. Perfect for those seeking an immersive experience, our sites provide opportunities for wildlife spotting, fishing, and peaceful relaxation. Escape the hustle and bustle of everyday life.',
    'Our campgrounds offer a variety of options for outdoor enthusiasts. From rustic tent sites to fully equipped RV spots, there’s something for everyone. Gather around the fire, share stories, and bask in the natural beauty that surrounds you.',
    'Discover adventure at our vibrant campgrounds, featuring scenic trails and diverse outdoor activities. Whether you’re a seasoned camper or new to camping, our sites provide a welcoming space to immerse yourself in nature and enjoy outdoor fun.',
    'Camp beneath towering trees and experience the serenity of our well-maintained campgrounds. With amenities like clean restrooms and picnic areas, your stay will be comfortable and memorable. Perfect for family outings and group getaways.',
    'Step into a world of peaceful camping at our picturesque campgrounds, where comfort meets nature. Ideal for stargazing, photography, and relaxation, our sites offer an unforgettable experience in the great outdoors.',
    'Our family-friendly campgrounds are designed to provide fun and adventure for all ages. From interactive nature programs for kids to hiking trails for adults, there’s something for everyone to enjoy. Embrace the beauty of nature together.',
    'Enjoy a serene camping experience at our remote campgrounds, where the only sounds you’ll hear are those of birds and rustling leaves. Perfect for those looking to escape the noise of modern life and immerse themselves in nature’s calm.',
    'Escape to our tranquil campgrounds and immerse yourself in nature’s peaceful embrace. Our sites offer a variety of activities, from canoeing on nearby lakes to guided nature walks, ensuring an enriching and rejuvenating experience.',
    'Experience the charm of rustic camping at our secluded campgrounds. Surrounded by nature’s beauty, enjoy simple pleasures like storytelling, nature walks, and star-gazing around a crackling fire.',
    'Our adventure-packed campgrounds are ideal for thrill-seekers. From zip-lining and rock climbing to wildlife observation, every moment is filled with excitement and discovery.',
    'For a peaceful and romantic escape, our serene campgrounds offer cozy spots perfect for couples. Enjoy intimate moments by the fire or explore scenic trails hand in hand.',
    'Immerse yourself in the wild with our campgrounds designed for nature lovers. Spot unique wildlife, bird watch, and hike through scenic trails to connect with the great outdoors.',
    'Our family-oriented campgrounds provide a safe environment for children to explore while creating lasting memories with loved ones. From scavenger hunts to marshmallow roasting, there’s fun for everyone.',
    'Embrace eco-friendly camping at our sustainable campgrounds. Enjoy the beauty of nature while supporting environmentally responsible practices and reducing your ecological footprint.',
    'Experience the best of both worlds with our beachside campgrounds. Combine camping with beach activities like swimming, beachcombing, and evening bonfires for a perfect seaside retreat.',
    'Step back in time at our historical campgrounds. Learn about local history, heritage, and enjoy old-fashioned camping traditions amidst historic landmarks and landscapes.',
    'For those seeking peace and solitude, our quiet campgrounds offer the perfect setting for reflection and mindfulness. Disconnect from the world and rejuvenate in a calm natural environment.',
    'Our versatile campgrounds cater to both adventure seekers and relaxation enthusiasts. Whether you prefer thrilling outdoor activities or peaceful moments of stillness, there’s something for everyone.',
    'Experience the joy of camping with breathtaking mountain views. Our campgrounds are a haven for hikers, climbers, and outdoor enthusiasts, offering stunning vistas and endless exploration opportunities.',
    'Unwind by the lakeside at our tranquil campgrounds, where you can fish, paddle, or simply relax by the water. The serene setting is perfect for families and solo adventurers alike.',
    'Discover the magic of seasonal camping at our scenic locations. Whether it’s the vibrant colors of autumn or the refreshing air of spring, our campgrounds offer a unique experience year-round.',
    'Connect with the night sky at our dark-sky campgrounds, perfect for stargazing and astrophotography. Witness the Milky Way like never before and marvel at the wonders above.',
    'Our pet-friendly campgrounds welcome your furry companions. Explore trails together, relax by the fire, and enjoy an unforgettable adventure with your four-legged friends.',
    'Adventure awaits at our riverside campgrounds, where you can kayak, raft, or swim in pristine waters. Experience the thrill of water-based activities alongside breathtaking natural beauty.',
    'Escape to the desert and camp under a canopy of stars. Our unique desert campgrounds offer a serene and otherworldly experience for those seeking solitude and inspiration.',
    'Bring your group together at our spacious campgrounds, ideal for reunions, corporate retreats, or team-building activities. Enjoy group-friendly amenities and a welcoming atmosphere.',
    'Experience the beauty of camping in the forest canopy with our treehouse campgrounds. Stay elevated and enjoy stunning views while immersed in the heart of nature.',
    'Discover the perfect balance of adventure and relaxation at our hot spring campgrounds. Soak in natural thermal pools after a day of exploring nearby trails and landscapes.',
    'Celebrate special occasions in the great outdoors at our event-friendly campgrounds. Whether it’s a birthday, wedding, or anniversary, our scenic locations provide an unforgettable backdrop.',
    'Reconnect with your roots at our cultural heritage campgrounds, where you can learn about local traditions, crafts, and cuisine while enjoying a unique camping experience.',
    'Camp at the edge of adventure in our cliffside campgrounds, offering dramatic views and heart-pounding experiences for thrill-seekers and photography enthusiasts.',
    'Recharge your soul at our wellness-focused campgrounds, featuring yoga sessions, meditation spots, and holistic activities designed to promote relaxation and rejuvenation.',
    'Discover a kid-friendly camping paradise with play areas, adventure courses, and engaging outdoor activities that will keep children entertained and inspired.',
    'Dive into the adventure of jungle camping at our exotic campgrounds. Explore lush rainforests, observe rare wildlife, and immerse yourself in the wonders of the tropics.',
    'Make memories at our themed campgrounds, featuring unique setups like cowboy-style ranches, enchanted forests, or pirate-inspired adventures. Fun for campers of all ages!',
    'Our inclusive campgrounds welcome campers of all abilities. With accessible facilities and activities, everyone can enjoy the beauty and tranquility of nature.',
    'Enjoy the comfort of luxury camping at our glamping sites. From cozy cabins to fully equipped tents, experience the outdoors without compromising on modern comforts.',
    'Experience the magic of winter camping at our snow-covered campgrounds. Build snowmen, enjoy sledding, and cozy up around the fire for a truly enchanting adventure.'
]